# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee9d3c0ecb3786963d00873c03f29310807e4b81e306c1fced643d2a097ef4eb4d4a17ae71bec0ffb2e0fa5b3c89fb587074935d5fee0e055221031bf679e56d

test:
  secret_key_base: cffa0135469ea6efcd9055399a8aafb55807765cbb0f7327c82e909ee193d2a4a89fa42d9434d042edcbcfff77929dcee5a1b75a9422eaf7aef0f6eb236cff0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
